In [15]:
import numpy as np
import pandas as pd
import torch.nn as nn
import matplotlib.pyplot as plt
import torch

In [114]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(2, 10),
            nn.ReLU(),
            nn.Linear(10, 2),
            nn.ReLU(),
            nn.Linear(2, 2)
        )

    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits


In [31]:
x = torch.tensor(list(range(100)),dtype=torch.float32)

In [36]:
x[1:2]

tensor([1.])

In [37]:
model(x[0:1])

tensor([-0.1168], grad_fn=<AddBackward0>)

In [108]:
X_train = torch.tensor([[0,0],[0,1],[1,0],[1,1]],dtype=torch.float32)
y_train = torch.tensor([0,1,1,0],dtype=torch.long)

In [106]:
y_train

tensor([0., 1., 1., 0.])

In [110]:
ce = nn.CrossEntropyLoss()
model = NeuralNetwork()
pred = model(X_train)

loss = ce(pred,y_train)
loss

tensor(0.6883, grad_fn=<NllLossBackward0>)

In [115]:
model = NeuralNetwork()
opt = torch.optim.Adam(model.parameters(),lr=.001)
ce = nn.CrossEntropyLoss()
loss=1
while loss>0.01:
        prediction = model(X_train)
        print(prediction)
        loss = ce(prediction,y_train)
        loss.backward()
        opt.step()
        opt.zero_grad()

tensor([[-0.3600,  0.6953],
        [-0.3901,  0.6622],
        [-0.3391,  0.6554],
        [-0.3180,  0.6747]], grad_fn=<AddmmBackward0>)
tensor([[-0.3573,  0.6936],
        [-0.3865,  0.6629],
        [-0.3361,  0.6554],
        [-0.3142,  0.6754]], grad_fn=<AddmmBackward0>)
tensor([[-0.3547,  0.6918],
        [-0.3829,  0.6636],
        [-0.3331,  0.6555],
        [-0.3105,  0.6761]], grad_fn=<AddmmBackward0>)
tensor([[-0.3521,  0.6901],
        [-0.3792,  0.6644],
        [-0.3302,  0.6555],
        [-0.3067,  0.6769]], grad_fn=<AddmmBackward0>)
tensor([[-0.3494,  0.6884],
        [-0.3755,  0.6651],
        [-0.3272,  0.6556],
        [-0.3029,  0.6776]], grad_fn=<AddmmBackward0>)
tensor([[-0.3468,  0.6867],
        [-0.3719,  0.6658],
        [-0.3242,  0.6557],
        [-0.2991,  0.6783]], grad_fn=<AddmmBackward0>)
tensor([[-0.3442,  0.6850],
        [-0.3682,  0.6664],
        [-0.3212,  0.6557],
        [-0.2953,  0.6790]], grad_fn=<AddmmBackward0>)
tensor([[-0.3416,  0.6833],

In [93]:
model(x[20:21])

tensor([39.5272], grad_fn=<AddBackward0>)